Repository PrestaShop/ps_facetedsearch, pull requests merged in 2019-10, with the labels that each got.

#143 Reset page filter when using slider
  src/Product/SearchProvider.php
  tests/php/FacetedSearch/Product/SearchProviderTest.php
  upgrade/upgrade-3.3.0.php
Labels: QA approved, bug

#133 Update for migrated Features create/edit form
  src/Form/Feature/FormDataProvider.php
  src/Form/Feature/FormModifier.php
  src/Hook/Feature.php
  tests/php/FacetedSearch/HookDispatcherTest.php
  tests/php/phpstan/phpstan.neon
  upgrade/upgrade-3.4.0.php
Labels: QA approved, enhancement

#144 Use public_name instead of name for attribute group
  src/Filters/Block.php
  src/Filters/Converter.php
  tests/php/FacetedSearch/Filters/BlockTest.php
Labels: QA approved, bug

#146 Use specific prestashop version for phpstan
  .travis.yml
  tests/php/phpstan/phpstan-1.7.1.2.neon
  tests/php/phpstan/phpstan-1.7.2.5.neon
  tests/php/phpstan/phpstan-1.7.3.4.neon
  tests/php/phpstan/phpstan-1.7.4.4.neon
  tests/php/phpstan/phpstan-1.7.5.1.neon
Labels: enhancement

#145 Fix url validation
  config/index.php
  config/services.yml
  src/Constraint/UrlSegment.php
  src/Constraint/UrlSegmentValidator.php
  src/Form/Feature/FormModifier.php
  tests/php/phpstan/phpstan-1.7.1.2.neon
  tests/php/phpstan/phpstan-1.7.2.5.neon
Labels: QA approved

#149 Clear cache button displays an error even on success
  ps_facetedsearch.php
Labels: QA approved
