Repository PrestaShop/ps_facetedsearch, pull requests merged in 2020-03, with the labels that each got.

#158 Show products only from default category - optional
  _dev/back/index.js
  ps_facetedsearch.php
  src/Product/Search.php
  tests/php/FacetedSearch/Product/SearchTest.php
  views/dist/back.js
  views/dist/back.js.map
  views/templates/admin/manage.tpl
Labels: PM ✔️, QA ✔️

#154 Sort products: InStock, available with qty 0, OutOfStock
  ps_facetedsearch.php
  src/Adapter/MySQL.php
  tests/php/FacetedSearch/Adapter/MySQLTest.php
  tests/php/phpunit.xml
  views/templates/admin/manage.tpl
Labels: QA ✔️

#165 Release 3.5.0
  README.md
  _dev/back/index.js
  _dev/cldr/number-formatter.js
  config.xml
  package-lock.json
  package.json
  ps_facetedsearch.php
  src/Adapter/MySQL.php
  src/Product/Search.php
  tests/js/cldr/number-formatter.spec.js
  tests/php/FacetedSearch/Adapter/MySQLTest.php
  tests/php/FacetedSearch/Product/SearchTest.php
  tests/php/phpunit.xml
  views/dist/back.js
  views/dist/back.js.map
  views/dist/front.js
  views/dist/front.js.map
  views/templates/admin/manage.tpl
Labels: QA ✔️

#166 remove trailing space
  views/templates/front/catalog/active-filters.tpl
Labels: bug
