Repository PrestaShop/ps_facetedsearch, pull requests merged in 2020-12, with the labels that each got.

#273 Fix PHPStan configuration
  .github/workflows/php.yml
Labels: bug

#274 Fixed invalid composer.json
  composer.json
Labels: bug

#276 Update phpstan to handle PS versions properly
  .github/workflows/php.yml
  tests/php/phpstan.sh
  tests/php/phpstan/phpstan-1.7.1.2.neon
  tests/php/phpstan/phpstan-1.7.2.5.neon
  tests/php/phpstan/phpstan-1.7.3.4.neon
  tests/php/phpstan/phpstan-1.7.4.4.neon
  tests/php/phpstan/phpstan-1.7.5.1.neon
  tests/php/phpstan/phpstan-1.7.6.9.neon
  tests/php/phpstan/phpstan-latest.neon
  tests/php/phpstan/phpstan.neon
Labels: enhancement

#271 Make sure custom feature values are loaded
  src/Filters/Block.php
  src/Filters/Converter.php
  tests/php/FacetedSearch/Filters/BlockTest.php
  views/dist/back.css.map
  views/dist/back.js
  views/dist/back.js.map
  views/dist/front.css.map
  views/dist/front.js
  views/dist/front.js.LICENSE.txt
  views/dist/front.js.map
  webpack.config.js
Labels: QA ✔️, bug

#239 Add flag to change the page is migrated
  src/Hook/Feature.php
Labels: QA ✔️, bug

#269 Replace ' ' with '\s' in filter label regex
  _dev/front/slider.js
  views/dist/front.js
  views/dist/front.js.map
Labels: QA ✔️, bug

#272 Only check the category name, ignore parent id
  src/Filters/Converter.php
Labels: QA ✔️, bug

#275 Correctly serialize and unserialize parameters in URLs.
  src/Filters/Converter.php
  src/Hook/ProductSearch.php
  src/Product/SearchProvider.php
  src/URLSerializer.php
  tests/php/FacetedSearch/Filters/ConverterTest.php
  tests/php/FacetedSearch/URLSerializerTest.php
  tests/php/phpstan/phpstan-1.7.6.9.neon
  tests/php/phpstan/phpstan-latest.neon
Labels: QA ✔️, bug

#189 Fix order by price indexation without tax rate (default country fix)
  ps_facetedsearch.php
Labels: QA ✔️, bug

#279 Bump version to 3.7.0
  config.xml
  ps_facetedsearch.php
Labels: enhancement

#289 The third parameter is about attribute and not country id
  ps_facetedsearch.php
Labels: bug

#294 Fix cs fixer action
  .github/workflows/php.yml
Labels: bug
