Repository PrestaShop/ps_facetedsearch, pull requests merged in 2020-07, with the labels that each got.

#170 Ajax update product list on select lists
  views/templates/front/catalog/facets.tpl
Labels: QA ✔️

#172 Added sort by bestsellers
  src/Adapter/MySQL.php
  src/Product/SearchProvider.php
  tests/php/FacetedSearch/Adapter/MySQLTest.php
Labels: PM ✔️, QA ✔️, enhancement

#177 Remove useless part of code
  ps_facetedsearch-price-indexer.php
  ps_facetedsearch.php
Labels: QA ✔️, bug
