Repository PrestaShop/ps_facetedsearch, pull requests merged in 2022-01, with the labels that each got.

#479 Enable filtering by stock properly
  src/Filters/Block.php
  src/Filters/Converter.php
  src/Filters/Products.php
  src/Product/Search.php
  tests/php/FacetedSearch/Filters/BlockTest.php
  tests/php/FacetedSearch/Product/SearchTest.php
Labels: enhancement, QA ✔️

#584 Improved Workflow Build Release
  .github/workflows/build-release.yml
Labels: enhancement

#586 Fix availability filter for products with negative quantities.
  src/Filters/Block.php
  src/Product/Search.php
  tests/php/FacetedSearch/Filters/BlockTest.php
  tests/php/FacetedSearch/Product/SearchTest.php
Labels: QA ✔️

#593 Fix `strip_tags` error messages during value escaping.
  src/Adapter/MySQL.php
Labels: QA ✔️

#603 Fix switch buttons
  _dev/back/blocklayered.scss
  views/dist/back.css
  views/dist/back.css.map
  views/dist/front.js
  views/dist/front.js.map
Labels: QA ✔️
