Repository PrestaShop/ps_facetedsearch, pull requests merged in 2023-08, with the labels that each got.

#886 Pass attribute information with the results
  src/Product/SearchProvider.php
Labels: QA ✔️

#884 Flush cache on upgrade
  upgrade/upgrade-3.13.0.php
Labels: QA ✔️

#893 Added `data-type` to distinguish facet
  views/templates/front/catalog/facets.tpl
Labels: enhancement, Waiting for QA

#902 Update GH workflows: Node 14-16, PHP 7.2-8.2, Github actions v3
  .github/workflows/js.yml
  .github/workflows/php.yml
Labels: Waiting for QA, waiting for author, waiting for dev

#895 Fix load JqueryUI for load good component - Link PR Prestashop #33563
  src/Hook/ProductSearch.php
Labels: QA ✔️
